version: '2.1'

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ingest.geoip.downloader.enabled: "false"
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: curl -s http://elastic:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 10

  esmigrator:
    image: gradle:7
    command: ./gradlew bootRun -x test --no-daemon
    working_dir: /app
    volumes:
      - app:/app
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elastic:9200
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "http://esmigrator:8080/actuator"]
      interval: 7s
      retries: 5
    depends_on:
      elastic:
        condition: service_healthy

volumes:
  app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_ROOT}