management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  elasticsearch:
    uris:
    - http://localhost:9200
    username: 
    password: 

logging:
  level:
    org:
      elasticsearch.client: TRACE
      springframework:
        data: INFO
